# ----
# Site

title: Annopolis
description: Annotation Server
url: https://github.com/yale-web-technologies/mirador-annotations
baseurl: https://github.com/yale-web-technologies/mirador-annotations/docs

google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: Documentation
    position: 1
  api:
    title: APIs
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
